env: dev
log_level: info
listen_address: :8800
#热更新配置文件
hot_reload: true
alert_type: "feishu" #platform "dingtalk","feishu"
#---------------------↓webhook-----------------------
open_dingding: 1 # 0 for off, 1 for on
dingding:
  dd_url: https://oapi.dingtalk.com/robot/send?access_token=xxxxx
#是否开启飞书告警通道,可同时开始多个通道0为关闭,1为开启
open_feishu: 1
feishu:
  msg_type: post
  fs_url: https://open.feishu.cn/open-apis/bot/v2/hook/bf8bb912-bc2e-40ad-9533-fcb8068aa621
feishu_robots:
  - name: robot1
    webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/bf8bb912-bc2e-40ad-9533-fcb8068aa621"
  - name: robot2
    webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/another-webhook-url"
templates:
  - name: default
    path: "templates/template.tmpl"
  - name: critical
    path: "templates/critical.tmpl"
elasticsearch:
  host:
  port:
  username:
  password:
db:
  driver: mysql
  database: jenkins
  username: root
  password: Unipal666
  host: 172.168.1.10
  port: 3306
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 3600
redis:
memcache:
